[package]
name = "haumaru"
version = "0.0.0"
authors = ["Shane Gibbs <shane@hands.net.nz>"]

[dependencies]
haumaru-api = { path = "api" }
log = "*"
env_logger = "*"
time = "*"
clap = "*"

[[bin]]
doc = false
name = "haumaru"
path = "src/bin/haumaru.rs"
